site_name: Tool Inventory

theme:
  name: material

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Tool Inventory: README.md
  - Learn: learn.md
  - Code Reference: reference/
  - Contributing: CONTRIBUTING.md
  - Reference: reference.md
  - Changelog: CHANGELOG.md
  - Code of Conduct: CODE_OF_CONDUCT.md

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          options:
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            separate_signature: true
            show_signature_annotations: true

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
  - footnotes
  - def_list
  - admonition
  - codehilite
  - pymdownx.extra
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed
